package com.untamedrealms.npcs.client;

import com.untamedrealms.npcs.data.NpcDef;
import com.untamedrealms.npcs.entity.NpcEntity;
import net.minecraft.client.model.HumanoidModel;
import net.minecraft.client.model.PlayerModel;
import net.minecraft.client.model.geom.ModelLayers;
import net.minecraft.client.renderer.entity.EntityRendererProvider;
import net.minecraft.client.renderer.entity.HumanoidMobRenderer;
import net.minecraft.client.renderer.entity.layers.HumanoidArmorLayer;
import net.minecraft.resources.ResourceLocation;

/** Renders NPCs with the player model and their archetype's skin (generated by ArtForge). */
public class NpcRenderer extends HumanoidMobRenderer<NpcEntity, PlayerModel<NpcEntity>> {
    private static final ResourceLocation FALLBACK = ResourceLocation.withDefaultNamespace("textures/entity/player/wide/steve.png");

    public NpcRenderer(EntityRendererProvider.Context context) {
        super(context, new PlayerModel<>(context.bakeLayer(ModelLayers.PLAYER), false), 0.5f);
        addLayer(new HumanoidArmorLayer<>(this,
                new HumanoidModel<>(context.bakeLayer(ModelLayers.PLAYER_INNER_ARMOR)),
                new HumanoidModel<>(context.bakeLayer(ModelLayers.PLAYER_OUTER_ARMOR)),
                context.getModelManager()));
    }

    @Override
    public ResourceLocation getTextureLocation(NpcEntity entity) {
        NpcDef def = entity.def();
        if (def == null) return FALLBACK;
        ResourceLocation skin = def.skin();
        // "urnpcs:blacksmith" -> urnpcs:textures/entity/npc/blacksmith.png; full texture paths pass through.
        if (skin.getPath().startsWith("textures/")) return skin;
        return ResourceLocation.fromNamespaceAndPath(skin.getNamespace(), "textures/entity/npc/" + skin.getPath() + ".png");
    }
}
