name = "Untamed Realms"
author = "Untamed Realms Team"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c0e2c4c7baf3dc6c0eee5f1c041da8692e006fb3d10ea17d1d1cb4a9d7b2f9c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"

[options]
acceptable-game-versions = ["1.21"]
