name = "Untamed Realms"
author = "Untamed Realms Team"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "669b5e63a934d0b06c21578a41d7ff0ec3e79658f2087fa34362e46f76d911dc"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"

[options]
acceptable-game-versions = ["1.21"]
